spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    hibernate:
      ddl-auto: create-drop
  output:
    ansi:
      enabled: always
logging:
  level:
    org.hibernate.type: trace